name: Tumblr Post Action
description: Automatically post to Tumblr via GitHub Actions
author: Actionslaw

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: type
  color: blue

# Define your inputs here.
inputs:
  blog-identifier:
    description: >
      Unique identifier for your blog. You can find your identifier by following
      this instructions here:
      https://www.tumblr.com/docs/en/api/v2#blog-identifiers
    required: true
  text:
    description: The text to post to Tumblr.
    required: true
  media:
    description: Folder containing images to post.
    required: false
  replyTo:
    description: >
      Identifier of the response to reply to in the format of:
      `post-id|tumblelog-uuid|reblog-key`.
    required: false
  tags:
    description: >
      JSON array of hashtags to post with.
    required: false
  consumer-key:
    description: >
      Consumer API key, available from the Tumblr OAuth applications page:
      https://www.tumblr.com/oauth/apps.
    required: true
  consumer-secret:
    description: >
      Consumer API secret key, available from the Tumblr OAuth applications
      page: https://www.tumblr.com/oauth/apps.
    required: true
  access-token:
    description: >
      Application access token, available from the Tumblr OAuth applications
      page: https://www.tumblr.com/oauth/apps.
    required: true
  access-token-secret:
    description: >
      Application access token secret, available from the Tumblr OAuth
      applications page: https://www.tumblr.com/oauth/apps.
    required: true

outputs:
  post-id:
    description: >
      Unique identifier of the post the can be used as input for replyTo, as
      above.

runs:
  using: node20
  main: dist/index.js
