name: Tumblr Post Action
description: Automatically post to Tumblr via Github Actions
author: Actionslaw

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: type
  color: blue

# Define your inputs here.
inputs:
  text:
    description: The text to post to Tumblr.
    required: true
  media:
    description: Folder containing images to post.
    required: false
  replyTo:
    description: URl of the post to reply to.
    required: false
  consumer-key:
    description: >
      Consumer API key, available from the Tumblr OAuth applications
      page: https://www.tumblr.com/oauth/apps.
    required: true
  consumer-secret:
    description: >
      Consumer API secret key, available from the Tumblr OAuth applications
      page: https://www.tumblr.com/oauth/apps.
    required: true
  access-token:
    description: >
      Application access token, available from the Tumblr OAuth applications
      page: https://www.tumblr.com/oauth/apps.
    required: true
  access-token-secret:
    description: >
      Application access token secret, available from the Tumblr OAuth applications
      page: https://www.tumblr.com/oauth/apps.
    required: true

runs:
  using: node20
  main: dist/index.js
